spring:

  datasource:
    url: jdbc:mysql://localhost:3306/midian?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&rewriteBatchedStatements=true&serverTimezone=UTC
    username: root
    password: zyq52041310
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximumPoolSize: 5