spring:
  application:
    name: provider
dubbo:
  application:
    name: provider
  registry:
    address: nacos://127.0.0.1:8848
  protocol:
    name: dubbo
    port: 20847
  consumer:
    check: false
    timeout: 3000
    retries: 0