spring:
  application:
    name: consumer
server:
  port: 8091
dubbo:
  application:
    name: consumer
  registry:
#    address: nacos://127.0.0.1:8848
    address: nacos://59.202.49.192:8102
  protocol:
    name: dubbo
    port: 20847
  consumer:
    check: false
    timeout: 3000
    retries: 0